title: "Omar's Blog"
author: "Eng. Omar Badawy"
description: "Doing what I love ðŸ’š."

email: "ce.omarbadawy@outlook.com"
github_username: "ce-omarbadawy"
linkedin_username: "omar-m-badawy"

##########################################################

theme: "minima"

# Base URL for GitHub Pages project site
baseurl: "/blog"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other

static_files:
  - assets/images/attachments/
